spring:
  application:
    name: my-spring
  profiles:
    default: local
  datasource:
    url: jdbc:mariadb://localhost:3308/luckydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.myspring.board.dto

logging:
  level:
    root: info
    org.springframework.cache: trace
    com.example.myspring.board.filter: trace